### ISSUE TITLE
NPM package does not contain built files

### ISSUE THREAD

**Issue by gius** [toiroakr/zod-empty#9]
Please check the published NPM package - it contains only the `src` folder. I guess you forgot to build it before publishing.

Thank you for the library!

**Comment by toiroakr** [comment]
Oh..., I forget to build before release...
Sorry for the silly mistake.

I fixed it [1.0.6](https://github.com/toiroakr/zod-empty/releases/tag/v1.0.6).
Please check it out.

Thank you for reporting!
